# 개발 프로필 설정
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/sns?autoReconnect=true&setTimezone=Asia/Seoul
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true

OAuth2:
  kakao:
    login-uri: https://kauth.kakao.com/oauth/authorize
    client-id: ${KAKAO_REST_API_KEY}
    redirect-uri: http://localhost:8081/login/kakao
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
