spring:
  profiles:
    group: # Run - Edit Configurations - Active Profiles에서 설정
      dev: common, dev
      prod: common, prod


---
spring:
  config:
    activate:
      on-profile: "common"
  application:
    name: demo
  mvc:
    view:
      suffix: .html
  sql:
    init:
      platform: mysql
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    database-platform: com.example.demo.common.config.CustomMySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    # generate-ddl: false
    open-in-view: false # @Transactional 선언된 서비스레이어 메서드 종료시 커넥션 반환



springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

jwt:
  secret-key: ajhsgerjhgbytf_!*fdhka**s-akgskdfksjfwfb345  # ${JWT_SECRET}

portOne:
  restApiKey: 0520324646366165 #${PORT_ONE_REST_API_KEY}
  secret: i8m41exe8tIvBKDzgc21Cyl9SYFcjUjPmKfBQ8fZnlMoefhjonm2wGgz5FOK0zQpFwPJt6mrsNV5CqfD #${PORT_ONE_SECRET}
  hostname: https://api.iamport.kr #${PORT_ONE_HOSTNAME}
---
spring:
  config:
    activate:
      on-profile: "prod"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://worklog.cu8wjp5j3wid.ap-northeast-2.rds.amazonaws.com:3306/demo # 변경해주세요
    username: admin #${LOCAL_DB_USERNAME}
    password: RhkdRhkdEhdEhd #${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
OAuth2:
  kakao:
    login-uri: https://kauth.kakao.com/oauth/authorize
    client-id: 44a90896f3ee78d0e03712d6cd025cfd #${KAKAO_REST_API_KEY}
    redirect-uri: https://worklog.shop/login/kakao
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/demo?autoReconnect=true&setTimezone=Asia/Seoul # 변경해주세요
    username: root # ${LOCAL_DB_USERNAME}
    password: 12345678 # ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
  devtools:
    livereload:
      enabled: true
OAuth2:
  kakao:
    login-uri: https://kauth.kakao.com/oauth/authorize
    client-id: 44a90896f3ee78d0e03712d6cd025cfd #${KAKAO_REST_API_KEY}
    redirect-uri: http://localhost:3000/login/kakao
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
server:
  port: 3000