# 프로필 공통 설정
spring:
  application:
    name: demo
  mvc:
    view:
      suffix: .html
  sql:
    init:
      platform: mysql
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    database-platform: com.example.demo.common.config.CustomMySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**
firebase:
  key: ${FIREBASE_KEY}
jwt:
  secret-key: ${JWT_SECRET}

port-one:
  rest-api-key: ${PORT_ONE_REST_API_KEY}
  secret: ${PORT_ONE_SECRET}
  hostname: ${PORT_ONE_HOSTNAME}
  customer-id: ${PORT_ONE_CUSTOMER_ID}

server:
  port: 8081